// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD68-tQrKDceMZ0A_iYooTp5_Q5Z_hRU4o',
    appId: '1:102483333758:web:aea8e10c40c3098a83fe2f',
    messagingSenderId: '102483333758',
    projectId: 'vocab-app-a8601',
    authDomain: 'vocab-app-a8601.firebaseapp.com',
    storageBucket: 'vocab-app-a8601.firebasestorage.app',
    measurementId: 'G-LZD5R0YER2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAxto3R1jZZzgbpFGuPZaZr_VL-OP3OQ',
    appId: '1:102483333758:android:aa14ae116c94347783fe2f',
    messagingSenderId: '102483333758',
    projectId: 'vocab-app-a8601',
    storageBucket: 'vocab-app-a8601.firebasestorage.app',
  );
}
